from enum import Enum


class IrisStatus(str, Enum):
    IRIS_OK = "IRIS_OK"
    IRIS_ERR_PACKET_TYPE = "IRIS_ERR_PACKET_TYPE"
    IRIS_ERR_MESSAGE_IN_PROGRESS = "IRIS_ERR_MESSAGE_IN_PROGRESS"
    IRIS_ERR_GOT_NO_RESPONSE = "IRIS_ERR_GOT_NO_RESPONSE"
    IRIS_ERR_NOT_IMPLEMENTED = "IRIS_ERR_NOT_IMPLEMENTED"
    IRIS_ERR_RESPONSE_WITHOUT_REQUEST = "IRIS_ERR_RESPONSE_WITHOUT_REQUEST"\

def returnOnError(status):
    if status != IrisStatus.IRIS_OK:
        return status
    else:
        pass